#!/bin/bash

sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 80 -j REDIRECT --to-port $1
sudo iptables -A PREROUTING -t nat -p tcp --dport 80 -j REDIRECT --to-ports $1

sudo iptables -t nat -A OUTPUT -o lo -p tcp --dport 443 -j REDIRECT --to-port $2
sudo iptables -A PREROUTING -t nat -p tcp --dport 443 -j REDIRECT --to-ports $2
